name = "ai-tools"
main = ".output/server/index.mjs"
compatibility_date = "2025-12-31"

[vars]
# Add non-secret variables here.
# Set secrets with:
#   wrangler secret put OPENAI_API_KEY
#   wrangler secret put MIYAKO_VECTOR_STORE_ID

[[d1_databases]]
binding = "MIYAKO_DB"
database_name = "miyako-gijiroku"
database_id = "07376f0e-60c5-4124-b363-a135d0c8821b"

[build]
command = "npm run build"

[assets]
directory = ".output/public"

